### PR TITLE
Update Twilio Video binding to 4.3.0

### PR DESCRIPTION
**Pull request by 4brunu**
Hi @dkornev
Thank you for this nice Twilio Video binding.
This PR updates the Twilio Video binding to 4.3.0.
Thanks

### CODE REVIEW

**Comment by 4brunu** [comment]
Some notes on this PR.
I needed to migrate from Carthage to Cocoapods, because Twilio Video 4.3.0 doesn't currently support Carthage.
https://www.twilio.com/docs/video/ios
So for this to work, it's needed to run `pod install` in `src` directory.

**Comment by 4brunu** [comment]
@dkornev did you get a chance to look at this? 🙂

**Comment by dkornev** [comment]
@4brunu Thank you very much for your work!
I only noticed few things missing there. You didn't create common interfaces like **ITVIAudioDevice** in the binding which leads to **cannot convert from 'Twilio.Video.iOS.TVIDefaultAudioDevice' to 'Twilio.Video.iOS.TVIAudioDevice'** error.

I'm going to merge your PR and add the interfaces missing.

Thank you

**Comment by 4brunu** [comment]
Thanks for taking the time to review and merge this PR 👍 
Looking forward to use this new version of TwilioVideo 🙂

**Pull request merged**
